### ISSUE TITLE
Allow users to opt out from tracking

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#150]
The Contact schema should be extended with a `do_not_track` boolean field. When it is set, URL redirects for click/open tracking are disabled.

- [ ] Add `do_not_track` field
- [ ] Disable link tracking for contacts with `do_not_track` enabled
- [ ] ? Enable logging for `do_not_track` opt-in/opt-out
- [ ] Add checkbox to form for tracking opt-in/opt-out - automatically set checkbox based on DNT headers
