### ISSUE TITLE
Allow tracking to be disabled

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#151]
It should be possible to disable tracking on a per-project and per-campaign basis. The project setting should be used as a default for new campaigns.

- [ ] Add setting to project settings
- [x] Add setting to campaign settings
- [x] Don't use link tracking when sending emails in non-tracked campaigns
- [x] Update campaign stats page to show that tracking was disabled

**Comment by wmnnd** [comment]
Implemented in #152.

**Comment by wmnnd** [comment]
Implemented in #152.
