### ISSUE TITLE
Add Click Tracking

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#53]
There should be a new Context, `Keila.Tracking`.

This context should have the following functions:

- [x] `register_link(campaign_id, url)`
- [x] `track_click(recipient_id, link_id)`
- [x] `track_open(recipient_id)`

**Comment by wmnnd** [comment]
Implemented via #54
